---
title: "Acerca de..."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Este sitio fue preparado por el equipo de Estadística de la FCA.


## Agustín Alesso

Ingeniero Agrónomo (UNL)
Dr. en Ciencias Agropecuarias (UNC)
`fontawesome::fa("email") calesso@fca.unl.edu.ar

Profesor Adjunto de la UNL. Orienta su investigación en métodos estadísticos y geoestadísticos aplicados a agricultura de precisión, y trabaja en temas relacionados con el análisis de la variabilidad espacial y temporal de rendimientos de cultivos y atributos de suelo y delimitación de zonas de manejo.


## Patricia Acetta

Ingeniera Agrónoma (UNL)
Mg. en Negocios Agroalimentarios (UNL)
`fontawesome::fa("email") pacetta@fca.unl.edu.ar

Ayudante de cátedra en grado, pregrado y posgrado de la UNL. Orienta su investigación en economía de la producción agropecuaria, análisis de datos de gestión económica y financiera y cambios tecnológicos de empresas agropecuarias, así como su impacto en la toma de decisiones en los agronegocios; formulación y evaluación de proyectos de desarrollo rural. Diplomada en AgroAnalytics (Univ. Austral). Especializada en Bioeconomía como nuevo pradigma de desarrollo productivo (IICA)